spring:
  datasource:
    url: jdbc:mysql://localhost:3306/CarRentalService
    username: root
    password: abcd1234

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    open-in-view: false